### ISSUE TITLE
.Net Standard 2.0 EOL?

### ISSUE THREAD

**Issue by jas88** [HicServices/FAnsiSql#149]
Oracle have now dropped support for .Net Standard 2.0, so we have to choose between current Oracle support and keeping .Net Standard 2.0. The other 3 (MSSQL, MySQL and Postgres) are still supporting 2.0 for now, but we should probably bite the bullet and switch to targeting 2.1 at some point...

**Comment by tznind** [comment]
2.1 seems sensible to me,

**Comment by jas88** [comment]
Fixed in #150
