### ISSUE TITLE
[postgres] ListDatabases fails if postgres DB does not exist

### ISSUE THREAD

**Issue by rkm** [HicServices/FAnsiSql#273]
The default `postgres` database may not always exist. This should use the specified database instead, if possible:

https://github.com/HicServices/FAnsiSql/blob/a893dce9bf0bfd4b83ca42369f9e42e7d9158c91/FAnsiSql/Implementations/PostgreSql/PostgreSqlServerHelper.cs#L64-L71

**Comment by jas88** [comment]
Should be fixed by #278 - turns out we need an explicit `null` Database for "don't connect to any specific database, just the engine as a whole" for this case, otherwise we have to guess at a database name which does actually exist.
