### ISSUE TITLE
Updating .Net SQL Server client

### ISSUE THREAD

**Issue by jas88** [HicServices/FAnsiSql#85]
System.Data.SqlClient being replaced by shiny new Microsoft.Data.SqlClient for new features and better .Net Core support - should FAnsi update to match? https://devblogs.microsoft.com/dotnet/introducing-the-new-microsoftdatasqlclient/

**Comment by tznind** [comment]
Depends if it is feature complete, worth looking though

**Comment by jas88** [comment]
Long term, the System.Data.SqlClient won't be getting new features, only security fixes, so the gap will grow over time. (Can't believe they only just added UTF-8 support, but it's in there now...)

**Comment by tznind** [comment]
Theres a breaking change between the two libraries.

`time` database fields need top be given `DbParameter` of Type `DateTime` in `System.Data.SqlClient` while in `Microsoft.Data.SqlClient` it is **must** be `TimeSpan`.  It is in line with the other ADO providers though, it was always hacky to have to convert to DateTime for SqlServer.

The change is in the PR e0ecfbea8e0820d873acb1cebb9fc6c82a924214
